//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduateEmploymentAssistanceService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class admins
    {
        public int id { get; set; }
        public string fullName { get; set; }
        public Nullable<long> phone { get; set; }
        public string password { get; set; }
        public Nullable<bool> isUser { get; set; }
        public string login { get; set; }
    }
}
